apiVersion: v1
kind: Namespace
metadata:
  name: colis-dev
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: c3madmin-portal
  namespace: colis-dev
  labels:
    app: c3madmin-portal
spec:
  replicas: 2 #We always want more than 1 replica for HA
  selector:
    matchLabels:
      app: c3madmin-portal
  template:
    metadata:
      labels:
        app: c3madmin-portal
    spec:
      containers:
        - name: c3madmin-portal #1st container
          image: tidusant/c3madmin-portal:latest #Dockerhub image
          ports:
            - containerPort: 8081 #Exposes the port 8901 of the container
          env:
            - name: SESSION_URI
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: devdb_url
            - name: SESSION_DB
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: devdb_name
            - name: AUTH_IP
              value: "c3m-grpc-auth-service.colis-dev.svc.cluster.local:8901"
            - name: SHOP_IP
              value: "c3m-grpc-shop-service.colis-dev.svc.cluster.local:8902"
---
kind: Service
apiVersion: v1
metadata:
  name: c3madmin-portal-service
  namespace: colis-dev
spec:
  type: NodePort
  selector:
    app: c3madmin-portal
  ports:
    - name: c3madmin-portal-port
      protocol: TCP
      port: 8081
      nodePort: 30081 #must be between 30000 - 32767
