# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details

orbs:
  aws-cli: circleci/aws-cli@1.3.1
# declare job name
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
      
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      
      - aws-cli/setup:
          profile-name: example
      - run: echo "Run your code here"

version: 2.1
workflows:
  aws-cli:
    jobs:
      #consume job name that declared above with ci context: aws
      - build:
          context: aws
